version: "3.0"
services:
  genshinUID:
    container_name: GenshinUID
    #build: ./docker
    image: treasurehighly/genshinuid:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./env.prod:/app/Nonebot2/.env.prod  #配置机器人的文件
      - ./ID_DATA.db:/app/Nonebot2/ID_DATA.db #数据库文件
      - ./accounts:/app/Nonebot2/accounts #插件、账号
      - ./data:/app/Nonebot2/data
#    deploy:     #如需对容器内存占用进行限制，请删除#自行控制（CPU部分可不限制，主要还是内存问题）
#      resources:
#        limits:
#          #cpus: '0.50'
#          memory: 1200M
    environment:
      - TZ=Asia/Shanghai
